BEGIN TRANSACTION;
DROP TABLE IF EXISTS `STATIONS`;
CREATE TABLE IF NOT EXISTS `STATIONS` (
	`id`	INTEGER,
	`name`	TEXT NOT NULL,
	PRIMARY KEY(`id`)
);
INSERT INTO `STATIONS` (id,name) VALUES (8032,'PARC');
INSERT INTO `STATIONS` (id,name) VALUES (8422,'BOTANIQUE');
INSERT INTO `STATIONS` (id,name) VALUES (8432,'ROGIER');
INSERT INTO `STATIONS` (id,name) VALUES (8764,'SIMONIS');
INSERT INTO `STATIONS` (id,name) VALUES (8774,'BELGICA');
COMMIT;
